name: libparallelproj_cuda

channels:
  - conda-forge

dependencies:
  - cxx-compiler
  - cuda-compiler
  - cmake
  - nanobind
  - numpy
  - array-api-compat
  - array-api-strict
  - pytest
  - cupy
  - pytorch=*=cuda*
