name: readthedocs
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - c-compiler
  - doxygen
  - cmake
  - ninja
  - sphinx>=7,<9
  - breathe
  - furo
  - nanobind
  - sphinxcontrib-bibtex
