name: readthedocs
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - sphinx>=7,<9
  - breathe
  - sphinx-gallery
  - furo
  - nanobind
  - sphinxcontrib-bibtex
  - matplotlib
  - array-api-compat
